on: 
  push:
    paths-ignore:
      - ".github/**"
      - ".devcontainer/**"

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependency
        run: yarn install --frozen-lockfile

      - name: Compile check
        run: tsc

      - name: Lint check
        run: yarn lint

      - name: Build check
        run: yarn build
      
      - name: Run unit test
        run: yarn test
